[update-changes] Add another release option that updates to next minor version.
`update-changes -r` now scans CHANGES for the most recent release
version, increases its minor version and uses that as the new version.

diff --git a/devel-tools/update-changes b/devel-tools/update-changes
--- a/devel-tools/update-changes
+++ b/devel-tools/update-changes
@@ -49,8 +49,9 @@ function usage
     echo "usage: `basename $0` [options]"
     echo
     echo "    -p <rev>    Explicitly name the past revision to compare with."
-    echo "    -R <tag>    Tag the current revision as a release. Use VERSION to use that."
-    echo "    -B <tag>    Tag the current revision as a beta release. Use VERSION to use that."
+    echo "    -R <tag>    Tag the current revision as a release. Update VERSION to use that."
+    echo "    -B <tag>    Tag the current revision as a beta release. Update VERSION to use that."
+    echo "    -r          Tag the current revision as a release, using the next minor version as version tag."
     echo "    -I          Initialize a new, initially empty CHANGES file."
     echo "    -c          Check whether CHANGES is up to date."
     echo "    -n          Do not amend the HEAD commit when feasible, create a new one."
@@ -262,6 +263,18 @@ EOF
    fi
 }
 
+function get_release_version {
+    # If $1 is provided, return that. Otherwise look for most recent release
+    # version in CHANGES and increase its minor version.
+    test -n "$1" && echo "$1" && return
+    old=$(cat $file_changes | egrep '^[0-9]*\.[0-9]*\.[0-9](-dev\.[0-9]+)? ' | cut -d ' ' -f 1 | head -1)
+    test -z "${old}" && echo "" && return
+    minor=$(echo ${old} | cut -d . -f 3)
+    minor=$((${minor} + 1))
+    new="$(echo ${old} | cut -d . -f 1-2).${minor}"
+    echo v${new}
+}
+
 ######
 
 last_rev=""
@@ -272,10 +285,16 @@ check=0
 quiet=0
 no_amends=0
 
-while getopts "hp:R:B:Icn" opt; do
+while getopts "hp:rR:B:Icn" opt; do
     case "$opt" in
         p) last_rev="$OPTARG";;
         R) release="$OPTARG";;
+        r) release=$(get_release_version);
+           if [ -z "${release}" ]; then
+            echo "Cannot determine release version."
+            exit 1
+            fi
+            ;;
         B) beta="$OPTARG";;
         I) init=1;;
         c) check=1; quiet=1;;
